wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.10
    cli_version: 0.17.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727679170
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 13
      - 23
      4: 3.10.10
      5: 0.17.6
      8:
      - 4
      - 5
      13: darwin-arm64
